//草の地面の色
#macro GROUND_GRASS_COLOR_R 198
#macro GROUND_GRASS_COLOR_G 218
#macro GROUND_GRASS_COLOR_B 113

//模様の色(地面の一つ上)
#macro GRASS_UPPER1_COLOR_R 198
#macro GRASS_UPPER1_COLOR_G 220
#macro GRASS_UPPER1_COLOR_B 113

//模様の色(地面の二つ上)
#macro GRASS_UPPER2_COLOR_R 216
#macro GRASS_UPPER2_COLOR_G 225
#macro GRASS_UPPER2_COLOR_B 111

//草原の洞窟の床
#macro DANGEON_GROUND_COLOR_R 144
#macro DANGEON_GROUND_COLOR_G 184
#macro DANGEON_GROUND_COLOR_B 191

#macro DANGEON_GROUND_NOISE1_COLOR_R 140
#macro DANGEON_GROUND_NOISE1_COLOR_G 182
#macro DANGEON_GROUND_NOISE1_COLOR_B 188

#macro DANGEON_GROUND_NOISE2_COLOR_R 138
#macro DANGEON_GROUND_NOISE2_COLOR_G 175
#macro DANGEON_GROUND_NOISE2_COLOR_B 185

//火山の床
#macro DANGEON_GROUND2_COLOR_R 110
#macro DANGEON_GROUND2_COLOR_G 80
#macro DANGEON_GROUND2_COLOR_B 86

#macro DANGEON_GROUND2_NOISE1_COLOR_R 119
#macro DANGEON_GROUND2_NOISE1_COLOR_G 86
#macro DANGEON_GROUND2_NOISE1_COLOR_B 93

#macro DANGEON_GROUND2_NOISE2_COLOR_R 95
#macro DANGEON_GROUND2_NOISE2_COLOR_G 70
#macro DANGEON_GROUND2_NOISE2_COLOR_B 75